"""S0 + S1: give the silo a name, and stamp it on everything we create (plans/SILO_MODEL.md).

A silo is a complete independent SaaS — its own tables, tenants and money — and until now it had no name
in the code at all. Readers inferred it from whichever tables they happened to be pointed at, which is
unverifiable and is the shape of every mode-isolation bug found on 2026-09-23.

These two phases are deliberately WRITE-ONLY. Nothing resolves or refuses on the stamp yet, so shipping
them cannot change any existing behaviour — the resolver (S3) lands separately, after the stamp has had
time to accumulate.
"""

import os
import unittest
from unittest.mock import patch

from handlers.checkout import build_checkout_payload
from stripe_link.silo import (
    KNOWN_SILOS,
    PRODUCTION,
    SANDBOX,
    current_silo,
    normalize_silo,
)


class SiloNameTests(unittest.TestCase):
    def test_the_two_silos_that_exist(self):
        self.assertEqual(KNOWN_SILOS, (SANDBOX, PRODUCTION))

    def test_an_explicit_setting_wins(self):
        with patch.dict(os.environ, {"SILO": "production", "ENVIRONMENT": "dev"}, clear=False):
            self.assertEqual(current_silo(), PRODUCTION)

    def test_a_stack_deployed_before_silos_existed_still_answers(self):
        # The ENVIRONMENT fallback covers the window where new code runs on an old stack. `dev` is a
        # DEPLOYMENT; `sandbox` is a silo — the mapping is exact today, which is what makes it safe.
        env = {k: v for k, v in os.environ.items() if k != "SILO"}
        env["ENVIRONMENT"] = "prod"
        with patch.dict(os.environ, env, clear=True):
            self.assertEqual(current_silo(), PRODUCTION)
        env["ENVIRONMENT"] = "dev"
        with patch.dict(os.environ, env, clear=True):
            self.assertEqual(current_silo(), SANDBOX)

    def test_an_unknown_silo_is_unknown_rather_than_defaulted(self):
        # Both directions of guess are wrong: calling production "sandbox" makes a silo foreign to
        # itself; calling sandbox "production" pollutes real data. So: no default.
        self.assertEqual(normalize_silo("staging"), "")
        self.assertEqual(normalize_silo(""), "")
        self.assertEqual(normalize_silo(None), "")

    def test_it_is_case_and_whitespace_forgiving(self):
        self.assertEqual(normalize_silo("  Production "), PRODUCTION)

    def test_nothing_configured_yields_nothing(self):
        with patch.dict(os.environ, {}, clear=True):
            self.assertEqual(current_silo(), "")


def _payload(**over):
    kwargs = dict(
        tenant_id="t1",
        offer={"offer_id": "o1", "checkout": {}},
        products_by_id={},
        resolved={"items": [], "currency": "usd"},
        success_url="https://x/s",
        cancel_url="https://x/c",
        mode="test",
    )
    kwargs.update(over)
    return build_checkout_payload(**kwargs)


class StampTests(unittest.TestCase):
    def test_a_session_says_which_silo_created_it(self):
        with patch.dict(os.environ, {"SILO": "production"}, clear=False):
            self.assertEqual(_payload()["metadata[silo]"], PRODUCTION)

    def test_a_subscription_carries_it_too(self):
        # A renewal is generated by Stripe months later and carries NONE of our metadata. The
        # subscription is the only place that can hold it for that event to find.
        recurring = {"kind": "service", "service_id": "s1", "currency": "usd", "unit_amount": 1000,
                     "label": "X", "recurring": {"interval": "month"}}
        with patch.dict(os.environ, {"SILO": "sandbox"}, clear=False):
            payload = _payload(resolved={"items": [recurring], "currency": "usd"})

        self.assertEqual(payload["mode"], "subscription")
        self.assertEqual(payload["subscription_data[metadata][silo]"], SANDBOX)

    def test_a_one_off_purchase_stamps_its_own_payment_intent(self):
        # S1b. Stripe does NOT propagate session metadata to the session's PaymentIntent — observed on
        # real objects 2026-09-23, where sessions carried `silo` and their PaymentIntents carried nothing.
        # It matters for events naming a CHARGE rather than a session: a refund, a dispute.
        with patch.dict(os.environ, {"SILO": "production"}, clear=False):
            payload = _payload()

        self.assertEqual(payload["payment_intent_data[metadata][silo]"], PRODUCTION)

    def test_a_subscription_does_not_get_payment_intent_data(self):
        # `payment_intent_data` is payment-mode only; Stripe rejects the combination.
        recurring = {"kind": "service", "service_id": "s1", "currency": "usd", "unit_amount": 1000,
                     "label": "X", "recurring": {"interval": "month"}}
        with patch.dict(os.environ, {"SILO": "production"}, clear=False):
            payload = _payload(resolved={"items": [recurring], "currency": "usd"})

        self.assertNotIn("payment_intent_data[metadata][silo]", payload)

    def test_an_unknown_silo_stamps_no_payment_intent_either(self):
        with patch.dict(os.environ, {}, clear=True):
            self.assertNotIn("payment_intent_data[metadata][silo]", _payload())

    def test_a_one_off_purchase_does_not_invent_a_subscription(self):
        with patch.dict(os.environ, {"SILO": "production"}, clear=False):
            payload = _payload()

        self.assertNotIn("subscription_data[metadata][silo]", payload)

    def test_an_unknown_silo_stamps_NOTHING(self):
        # A wrong stamp is worse than none: the read rule (unstamped means sandbox, never production) is
        # written down in exactly one place, and a guess here would quietly bypass it.
        with patch.dict(os.environ, {}, clear=True):
            payload = _payload()

        self.assertNotIn("metadata[silo]", payload)

    def test_the_upsell_payment_intent_is_stamped_too(self):
        # A one-click upsell is a PaymentIntent we create directly, not a session.
        source = (__import__("pathlib").Path(__file__).resolve().parents[1]
                  / "src/handlers/upsell.py").read_text(encoding="utf-8")

        self.assertIn('"metadata[silo]": current_silo()', source)

    def test_nothing_reads_the_stamp_yet(self):
        """S1 is write-only ON PURPOSE. When the resolver (S3) lands this test is deleted, not edited —
        it exists to make shipping the stamp ahead of the reader provably safe."""
        import pathlib
        import re

        root = pathlib.Path(__file__).resolve().parents[1] / "src"
        readers = []
        for path in root.rglob("*.py"):
            for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
                if re.search(r'(get|metadata)\s*\(?\s*["\']silo["\']', line):
                    readers.append(f"{path.relative_to(root)}:{n}")
        self.assertEqual(readers, [], "something reads metadata[silo] — S3 has begun, retire this test")


if __name__ == "__main__":
    unittest.main()
