"""Regenerate src/stripe_link/domain/network_icons.py from the simple-icons package.

Run: python3 scripts/generate_network_icons.py

Brand marks are NOT hand-authored. Path data typed from memory produces a shape that is subtly wrong in a
way nobody notices until it is on every tenant's page, and a brand mark is the one glyph where "close
enough" is not a thing. simple-icons is the maintained upstream (CC0-1.0, public domain), so this script
pulls it into a temp directory, extracts only the hosts we actually support, and writes a committed Python
table. Nothing at runtime -- or at deploy -- depends on npm.

Some hosts have no upstream icon: LinkedIn and Twitter were removed from simple-icons after trademark
requests from their owners, and the BBB was never added. `twitter.com` maps to the X mark because it is the
same service under a new name -- a twitter.com URL redirects to x.com today.

LinkedIn's mark is DRAWN instead, in `domain/network_icons_manual.py`. The removal request is about one
library redistributing the asset; it is not a rule against showing a LinkedIn icon on a link to a LinkedIn
profile, which is ordinary nominative use. That file is hand-authored and separate BECAUSE this script
rewrites its output wholesale -- anything added to network_icons.py by hand is destroyed on the next run.
"""
import json
import pathlib
import subprocess
import sys
import tempfile

# host -> simple-icons slug. The KEYS must be a subset of NETWORK_LABELS; the test enforces it, because a
# glyph needs a name to put in its aria-label.
#
# NOT a subset of SAME_AS_HOSTS, and deliberately so. A glyph says "you recognise this place"; the identity
# allowlist says "this may be asserted as who the tenant IS". Snapchat and OnlyFans are on a creator's hub
# constantly and could never be a sameAs, so coupling the two tables would have meant spelling out exactly
# the links a link hub exists to show.
HOST_SLUGS = {
    "crunchbase.com": "crunchbase",
    "facebook.com": "facebook",
    "github.com": "github",
    "instagram.com": "instagram",
    "onlyfans.com": "onlyfans",
    "pinterest.com": "pinterest",
    "snapchat.com": "snapchat",
    "threads.net": "threads",
    "tiktok.com": "tiktok",
    "trustpilot.com": "trustpilot",
    "twitter.com": "x",
    "wikidata.org": "wikidata",
    "wikipedia.org": "wikipedia",
    "x.com": "x",
    "yelp.com": "yelp",
    "youtube.com": "youtube",
}

OUTPUT = pathlib.Path(__file__).resolve().parents[1] / "src" / "stripe_link" / "domain" / "network_icons.py"

EXTRACT_JS = """
const si = require('simple-icons');
const slugs = %s;
const out = {};
for (const [host, slug] of Object.entries(slugs)) {
  const key = 'si' + slug.charAt(0).toUpperCase() + slug.slice(1);
  const icon = si[key];
  if (!icon) { console.error('MISSING ' + slug); process.exit(1); }
  out[host] = icon.path;
}
process.stdout.write(JSON.stringify(out));
"""


def main() -> int:
    with tempfile.TemporaryDirectory() as workdir:
        subprocess.run(
            ["npm", "install", "--silent", "--no-audit", "--no-fund", "simple-icons@16"],
            cwd=workdir, check=True,
        )
        result = subprocess.run(
            ["node", "-e", EXTRACT_JS % json.dumps(HOST_SLUGS)],
            cwd=workdir, check=True, capture_output=True, text=True,
        )
    paths = json.loads(result.stdout)
    lines = [
        '"""Brand glyphs for the social networks a link-in-bio row can show.',
        "",
        "GENERATED by scripts/generate_network_icons.py from simple-icons (CC0-1.0). Do not hand-edit: run the",
        "script. Path data is 24x24, single-path, currentColor -- the renderer supplies the <svg> wrapper and the",
        "accessible name, so nothing here carries presentation.",
        "",
        "Hosts absent from this table fall back to their worded label. That is not a gap: LinkedIn and Twitter",
        "were REMOVED from simple-icons at their owners' request, so shipping a mark for them would be using a",
        "logo whose owner asked for it not to be redistributed.",
        '"""',
        "",
        "NETWORK_ICON_PATHS = {",
    ]
    for host in sorted(paths):
        lines.append(f'    "{host}": "{paths[host]}",')
    lines.append("}")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(paths)} glyphs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
